### ISSUE TITLE
Build cake

### ISSUE THREAD

**Issue by Gani-23** [duck-dev/VocabularyTrainer#1]
Hi,
I was just wondering if you can write cake in a single build.cake that generates and deploy DMG file for mac and Exe for windows i have been working for avalonia cross platform and i been working on that since 3 days and i have no leads as now can you help me ?

**Comment by duck-dev** [comment]
Hello @Nani-7989 ,

is your question related to _Vocabulary Trainer_ or are you asking about your own project? Please only use issues here that are directly related to the repository. There are enough forums, communities and places in general where you can get help with any kind of technology or programming language.

For your information: A release with deployed packages of _Vocabulary Trainer_ for Windows, MacOS and Linux will be created soon, so that _Vocabulary Trainer_ can be used for free.
